apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: liquidation-heatmap
  description: liquidation_heatmap repository
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags: []
spec:
  type: service
  lifecycle: production
  owner: user:default/sam
  system: claude-infrastructure
