apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: liquidation-heatmap
  description: liquidation_heatmap repository
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gptcompany/LiquidationHeatmap
    github.com/workflows-folder: .github/workflows
  tags: []
spec:
  type: service
  lifecycle: production
  owner: user:default/sam
  system: claude-infrastructure
